version: "3.7"
services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always # avoid downtime
    volumes:
          - ./mongodb/data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - 27017:27017
    #command: #--logpath=/dev/null # --quiet

  # creates a database and pre-fills it with some data for testing
  mongo-init:
    build: ./mongodb/mongo-init # executes the mongo init script with it's own Dockerfile
    depends_on:
      - mongo

  spring:
    build: ./SpringBootApplication # location of the Dockerfile for Spring
    restart: always # avoid downtime
    image: philjay/springbootapp
    container_name: spring
    restart: always
    environment:
       - "SPRING_PROFILES_ACTIVE=production" # use Spring 'production' profile when deployed
    ports:
      - 8080:8080
    depends_on:
      - mongo-init

  angular:
    build: ./AngularApplication # location of the Dockerfile for Angular
    container_name: angular
    restart: always # avoid downtime
    ports:
      - 4200:4200
    depends_on:
      - mongo-init
