spring:
  profiles:
    active: test
  application:
    name: Server
server:
  ssl:
    key-store: classpath:other/keystore.jks
    key-store-password: keystore_password
    key-store-type: jks
    key-alias: key_alias
    key-password: key_password
    enabled: false #set to true here to enable
    port: 8443
crypto:
  algorithm: AES
  key: 12345678912345678912345678955555
